-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 15:53:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  -- `id_users` INT NOT NULL AUTO_INCREMENT,
  -- `username` VARCHAR(45) NULL,
  -- `password` VARCHAR(255) NULL,
  -- `foto` VARCHAR(255) NULL,
  -- PRIMARY KEY (`id_users`),
  -- UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id_kategori` INT NOT NULL AUTO_INCREMENT,
  `nama_kategori` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kategori`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id_buku` INT NOT NULL AUTO_INCREMENT,
  `kategori_id` INT NULL,
  `nama_buku` VARCHAR(45) NULL,
  `tersedia` BIGINT NULL DEFAULT 0,
  `dipinjam` BIGINT NULL DEFAULT 0,
  PRIMARY KEY (`id_buku`),
  INDEX `category_idx` (`kategori_id` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`kategori_id`)
    REFERENCES `mydb`.`categories` (`id_kategori`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pinjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pinjaman` (
  `id_pinjaman` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL,
  `siswa_id` INT NULL,
  `jumlah` INT NULL,
  PRIMARY KEY (`id_pinjaman`),
  INDEX `books_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `books`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`books` (`id_buku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
